sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  # for now, let's test only with H2
  #postgresql: '9.4'
  #mariadb: '10.0'
  apt:
    packages:
      - oracle-java8-installer
# might be useful to push reports to an S3 bucket
#  artifacts:
#    paths:
#      - $(find $HOME -name surefire-reports | tr "\n" ":")
#      - $(find $HOME -name failsafe-reports | tr "\n" ":")
#  s3_region: 'us-west-2'
cache:
  directories:
    - $HOME/.m2
env:
  - DB=h2
  # for now, let's test only with H2
  #- DB=pgsql
  #- DB=mariadb
install:
  # The Maven install provided by Travis is outdated, use Maven wrapper to get the latest version
  - mvn -N io.takari:maven:wrapper
  - ./mvnw -v
  # first run to download all the Maven dependencies without logging
  - ./mvnw -s settings-example.xml -B -q clean install -DskipTests=true
  # we run checkstyle first to fail fast if there is a styling error
  - ./mvnw -s settings-example.xml checkstyle:check
before_script: 
  - if [[ "$DB" == "pgsql" ]]; then psql -U postgres -f 'travis/pgsql.sql';fi 
  - if [[ "$DB" == "mariadb" ]]; then mysql -u root < 'travis/mariadb.sql'; fi
script:
  - if [[ "$DB" == "h2" ]]; then ./mvnw -s settings-example.xml -Pdocs,dist clean install;fi
  - if [[ "$DB" == "pgsql" ]]; then ./mvnw -s settings-example.xml -Pci-postgresql,docs,dist clean install;fi
  - if [[ "$DB" == "mariadb" ]]; then ./mvnw -s settings-example.xml -Pci-mariadb,docs,dist clean install; fi
